### ISSUE TITLE
Dataset Preprosessing

### ISSUE THREAD

**Issue by AlanXU07** [JoshuaChou2018/SkinGPT-4#2]
How did you prepare the dataset in stage 1?
What is the final data structure?

**Comment by JoshuaChou2018** [comment]
please check dataset/*.md, we prepared the skin dataset the same way as cc_sbu and laion.

**Comment by jyw2000-jyw** [comment]
Hi! How should I solve this problem?

Traceback (most recent call last):
  File "/home/yjiang056/projects/SkinGPT-4/demo.py", line 55, in <module>
    cfg = Config(args)
  File "/home/yjiang056/projects/SkinGPT-4/minigpt4/common/config.py", line 30, in __init__
    model_config = self.build_model_config(config, **user_config)
  File "/home/yjiang056/projects/SkinGPT-4/minigpt4/common/config.py", line 62, in build_model_config
    assert model_cls is not None, f"Model '{model.arch}' has not been registered."
AssertionError: Model 'skin_gpt4' has not been registered.

Thank u!
