### ISSUE TITLE
model register problem

### ISSUE THREAD

**Issue by jyw2000-jyw** [JoshuaChou2018/SkinGPT-4#3]
Hi! How should I solve this problem?

Traceback (most recent call last):
File "/home/yjiang056/projects/SkinGPT-4/demo.py", line 55, in
cfg = Config(args)
File "/home/yjiang056/projects/SkinGPT-4/minigpt4/common/config.py", line 30, in init
model_config = self.build_model_config(config, **user_config)
File "/home/yjiang056/projects/SkinGPT-4/minigpt4/common/config.py", line 62, in build_model_config
assert model_cls is not None, f"Model '{model.arch}' has not been registered."
AssertionError: Model 'skin_gpt4' has not been registered.

Thank u!

**Comment by JoshuaChou2018** [comment]
Hi, we have released the new version based on llama2
